# Generated by Django 2.2.5 on 2019-10-28 05:58

from django.db import migrations, models
import django.db.models.deletion
import myproject.apps.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('model_number', models.CharField(max_length=30, unique=True)),
                ('power', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=20)),
                ('certificate', models.CharField(blank=True, max_length=100)),
                ('accessory', models.CharField(blank=True, max_length=255)),
                ('fob', models.CharField(blank=True, max_length=30)),
                ('cif', models.CharField(blank=True, max_length=30)),
                ('product_dimension', models.CharField(blank=True, max_length=30)),
                ('giftbox_dimension', models.CharField(blank=True, max_length=30)),
                ('master_carton_dimension', models.CharField(blank=True, max_length=30)),
                ('net_weight', models.CharField(blank=True, max_length=30)),
                ('gross_weight', models.CharField(blank=True, max_length=30)),
                ('cap_20gp', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_40gp', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_40hq', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=myproject.apps.products.models.photo_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.Product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
