# Generated by Django 2.2.5 on 2019-10-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='is_available',
        ),
    ]
