# Generated by Django 2.2.5 on 2019-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='productphoto',
            old_name='photo',
            new_name='image_file',
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
