# Generated by Django 2.2.5 on 2019-10-14 10:46

from django.db import migrations, models
import myproject.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191014_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image_file',
            field=models.FileField(upload_to=myproject.apps.products.models.photo_directory_path),
        ),
    ]
