# Generated by Django 2.2.5 on 2019-10-21 03:37

from django.db import migrations, models
import myproject.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image_file',
            field=models.ImageField(upload_to=myproject.apps.products.models.photo_directory_path),
        ),
    ]
